
```{r}
library(tidyverse)
library(sf)
library(here)
library(stars)
library(tmap)
```

# Research Question
How does potential exposure to wastewater discharge


```{r}
# Reading in data
ejscreen <- sf::st_read(here::here(
  "data",
  "ejscreen",
  "EJSCREEN_2023_BG_StatePct_with_AS_CNMI_GU_VI.gdb"
))

# Filtering to Monterey County
monterey <- ejscreen %>%
  dplyr::filter(CNTY_NAME %in% c("Monterey County"))
```

```{r}
# Filtering to columns to explore
mc <- monterey |>
  filter(ACSTOTPOP > 0) |>
  select(
    ID,
    ACSTOTPOP,
    AREALAND,
    P_PM25,
    P_OZONE,
    P_DSLPM,
    P_CANCER,
    P_RESP,
    P_RSEI_AIR,
    P_PTRAF,
    P_LDPNT,
    P_PNPL,
    P_PRMP,
    P_PTSDF,
    P_UST,
    P_PWDIS,
    DEMOGIDX_2,
    PEOPCOLORPCT,
    P_LINGISOPCT,
    P_LOWINCPCT
  )
```


```{r}
# Exploring graphs of columns

tm_shape(mc) +
  tm_polygons(fill = "ACSTOTPOP")

tm_shape(mc) +
  tm_polygons(fill = "AREALAND")

tm_shape(mc) +
  tm_polygons(fill = "P_PM25")

tm_shape(mc) +
  tm_polygons(fill = "P_OZONE")

tm_shape(mc) +
  tm_polygons(fill = "P_DSLPM")

tm_shape(mc) +
  tm_polygons(fill = "P_CANCER")

tm_shape(mc) +
  tm_polygons(fill = "P_RESP")

tm_shape(mc) +
  tm_polygons(fill = "P_RSEI_AIR")

tm_shape(mc) +
  tm_polygons(fill = "P_PTRAF")

tm_shape(mc) +
  tm_polygons(fill = "P_LDPNT")

tm_shape(mc) +
  tm_polygons(fill = "P_PNPL")

tm_shape(mc) +
  tm_polygons(fill = "P_PRMP")

tm_shape(mc) +
  tm_polygons(fill = "P_PTSDF")

tm_shape(mc) +
  tm_polygons(fill = "P_UST")

tm_shape(mc) +
  tm_polygons(fill = "P_PWDIS")

tm_shape(mc) +
  tm_polygons(fill = "DEMOGIDX_2")

tm_shape(mc) +
  tm_polygons(fill = "PEOPCOLORPCT")

tm_shape(mc) +
  tm_polygons(fill = "P_LINGISOPCT")

tm_shape(mc) +
  tm_polygons(fill = "P_LOWINCPCT")
```


```{r}
# Narrowed down columns to keep exploring

tm_shape(mc) +
  tm_polygons(fill = "ACSTOTPOP")

tm_shape(mc) +
  tm_polygons(fill = "AREALAND")

tm_shape(mc) +
  tm_polygons(fill = "P_PWDIS")

tm_shape(mc) +
  tm_polygons(fill = "DEMOGIDX_2")

tm_shape(mc) +
  tm_polygons(fill = "P_PTRAF")

tm_shape(mc) +
  tm_polygons(fill = "P_PRMP")

tm_shape(mc) +
  tm_polygons(fill = "PEOPCOLORPCT")

tm_shape(mc) +
  tm_polygons(fill = "P_LINGISOPCT")

tm_shape(mc) +
  tm_polygons(fill = "P_LOWINCPCT")
```

```{r}
# Narrowed down columns of interest

tm_shape(mc) +
  tm_polygons(fill = "ACSTOTPOP")

tm_shape(mc) +
  tm_polygons(fill = "AREALAND")

tm_shape(mc) +
  tm_polygons(fill = "P_PWDIS")

tm_shape(mc) +
  tm_polygons(fill = "P_PRMP")

tm_shape(mc) +
  tm_polygons(fill = "DEMOGIDX_2")

tm_shape(mc) +
  tm_polygons(fill = "PEOPCOLORPCT")

tm_shape(mc) +
  tm_polygons(fill = "P_LINGISOPCT")

tm_shape(mc) +
  tm_polygons(fill = "P_LOWINCPCT")
```


```{r}
# Creating Scatterplots to analyze relationships

ggplot(
  data = mc,
  mapping = aes(
    x = DEMOGIDX_2,
    y = P_PWDIS
  )
) +
  geom_point()
```

```{r}
ggplot(
  data = mc,
  mapping = aes(
    x = PEOPCOLORPCT,
    y = P_PWDIS
  )
) +
  geom_point()
```

```{r}
ggplot(
  data = mc,
  mapping = aes(
    x = P_LINGISOPCT,
    y = P_PWDIS
  )
) +
  geom_point()
```

```{r}
ggplot(
  data = mc,
  mapping = aes(
    x = P_LOWINCPCT,
    y = P_PWDIS
  )
) +
  geom_point()
```

```{r}
ggplot(
  data = mc,
  mapping = aes(
    x = DEMOGIDX_2,
    y = P_PRMP
  )
) +
  geom_point()
```

```{r}
ggplot(
  data = mc,
  mapping = aes(
    x = PEOPCOLORPCT,
    y = P_PRMP
  )
) +
  geom_point()
```

```{r}
ggplot(
  data = mc,
  mapping = aes(
    x = P_LINGISOPCT,
    y = P_PRMP
  )
) +
  geom_point()
```

```{r}
ggplot(
  data = mc,
  mapping = aes(
    x = P_LOWINCPCT,
    y = P_PRMP
  )
) +
  geom_point()
```


```{r}
# Narrowed down to environmental variable of interest
# Highest to lowest relationship:
# DEMOGIDX_2, PEOPCOLORPCT, P_LOWINCPCT

ggplot(
  data = mc,
  mapping = aes(
    x = DEMOGIDX_2,
    y = P_PRMP
  )
) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)
```

```{r}
ggplot(
  data = mc,
  mapping = aes(
    x = PEOPCOLORPCT,
    y = P_PRMP
  )
) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)
```

```{r}
ggplot(
  data = mc,
  mapping = aes(
    x = P_LOWINCPCT,
    y = P_PRMP
  )
) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)
```

```{r}
ggplot(
  data = mc,
  mapping = aes(
    x = P_LINGISOPCT,
    y = P_PRMP
  )
) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)
```


```{r}
# Filtering to columns of interest
mc <- monterey |>
  filter(ACSTOTPOP > 0) |>
  select(
    ID,
    ACSTOTPOP,
    AREALAND,
    P_PRMP,
    DEMOGIDX_2,
    PEOPCOLORPCT,
    P_LINGISOPCT,
    P_LOWINCPCT
  )
```

```{r}
# Checking CRS for EJ dataset

st_crs(mc)
```

```{r}
# Creating st_point for cities with higher populations in Monterey County

salinas_p <- st_point(c(-121.632, 36.694))
monterey_p <- st_point(c(-121.880, 36.592))
seaside_p <- st_point(c(-121.819, 36.622))
marina_p <- st_point(c(-121.789, 36.682))
soledad_p <- st_point(c(-121.322, 36.430))
greenfield_p <- st_point(c(-121.245, 36.325))
kc_p <- st_point(c(-121.127, 36.216))
cbts_p <- st_point(c(-121.922, 36.554))
cv_p <- st_point(c(-121.726, 36.484))
bradley_p <- st_point(c(-120.869, 35.863))
ml_p <- st_point(c(-121.785, 36.805))
pajaro_p <- st_point(c(-121.741, 36.902))
castroville_p <- st_point(c(-121.752, 36.766))
chualar_p <- st_point(c(-121.516, 36.570))
bs_p <- st_point(c(-121.808, 36.270))
sl_p <- st_point(c(-121.021, 36.128))
sa_p <- st_point(c(-120.906, 36.020))
jolon_p <- st_point(c(-121.176, 35.971))
spreckels_p <- st_point(c(-121.647, 36.622))
spence_p <- st_point(c(-121.554, 36.623))
gonzalez_p <- st_point(c(-121.439, 36.516))
ch_p <- st_point(c(-121.934, 36.507))
hc_p <- st_point(c(-121.869, 36.534))
rtg <- st_point(c(-121.804, 36.527))
pb_p <- st_point(c(-121.944, 36.587))
pg_p <- st_point(c(-121.920, 36.619))
cdt_p <- st_point(c(-121.765, 36.569))
sb_p <- st_point(c(-121.708, 36.569))
sv_p <- st_point(c(-121.699, 36.603))
eg_p <- st_point(c(-121.735, 36.654))
prunedale_p <- st_point(c(-121.655, 36.803))
aromas_p <- st_point(c(-121.664, 36.865))
greenfield_p <- st_point(c(-121.246, 36.320))
pine_p <- st_point(c(-121.150, 36.181))
cvh_p <- st_point(c(-121.937, 36.482))


# Adding coordinate reference system

mc_points <- st_sfc(
  c(
    salinas_p,
    monterey_p,
    seaside_p,
    marina_p,
    soledad_p,
    greenfield_p,
    kc_p,
    cbts_p,
    cv_p,
    bradley_p,
    ml_p,
    pajaro_p,
    castroville_p,
    chualar_p,
    bs_p,
    sl_p,
    sa_p,
    jolon_p,
    spreckels_p,
    spence_p,
    gonzalez_p,
    hc_p,
    rtg,
    pb_p,
    pg_p,
    cdt_p,
    sb_p,
    sv_p,
    eg_p,
    prunedale_p,
    aromas_p,
    greenfield_p,
    pine_p,
    cvh_p
  ),
  crs = 4326
)
```

```{r}
# Transforming the CRS of Monterey county cities dataframe to match the CRS of the Monterey dataframe
mc_cities <- st_transform(mc_points, crs = st_crs(mc))
```

```{r}
# Verifying CRS match
if (st_crs(mc_cities) == st_crs(mc)) {
  print("it's a match!")
} else {
  print("still not a match")
}
```



```{r}
#| fig-width: 10
#| fig-height: 7

# Linguistics map 2nd version

# Linguistic isolation and high RMP proximity map
high_h <- mc |>
  filter(P_PRMP >= 80)

tm_shape(mc) +
  tm_polygons(
    fill = "P_LINGISOPCT",
    fill.legend = tm_legend(
      title = "Limited English-Speaking Households Percentile",
      frame = FALSE,
      bg = FALSE
    )
  ) +
  tm_shape(high_h) +
  tm_borders(
    col = "orangered3",
    lwd = 1
  ) +
  tm_shape(mc_cities) +
  tm_bubbles(
    size = .4,
    fill = "deepskyblue1",
    col = "black"
  ) +
  tm_add_legend(
    type = "lines",
    title = "",
    col = "orangered3",
    labels = "High RMP Proximity Census Blocks"
  ) +
  tm_add_legend(
    type = "symbols",
    title = "",
    fill = "deepskyblue1",
    col = "black",
    labels = "Communities"
  ) +
  tm_scalebar(position = c("left", "bottom")) +
  tm_compass(position = c("right", "top")) +
  tm_title_out(
    text = "Limited English-Speaking Households and Proximity to Hazardous Materials Facilities in Monterey County",
    fontface = "bold",
    position = tm_pos_out(
      cell.h = "center",
      cell.v = "top",
      pos.h = "center"
    )
  ) +
  tm_layout(
    text.fontfamily = "sans",
    style = "natural",
    bg.color = "grey95",
    frame = TRUE,
    legend.text.size = 0.58,
    legend.title.size = 0.6,
    title.size = 1.2,
    outer.margins = c(0.01, 0.01, 0.01, 0.01),
    asp = 0
  )
```

```{r}
# High RMP + High POC

poc_hazards <- filter(mc, P_PRMP >= 80 & PEOPCOLORPCT >= 0.65)

# High POC

poc <- filter(mc, PEOPCOLORPCT >= 0.65 & P_PRMP < 80)

# High RMP
hazards <- filter(mc, P_PRMP >= 80 & PEOPCOLORPCT < 0.65)

# NA

low <- filter(mc, P_PRMP < 80 & PEOPCOLORPCT < 0.65)
```

```{r}
#| fig-width: 10
#| fig-height: 7

tm_shape(mc) +
  tm_borders(lwd = 2) +
  tm_shape(poc_hazards) +
  tm_polygons(fill = "#e84614") +
  tm_shape(poc) +
  tm_polygons(fill = "#02bea5") +
  tm_shape(hazards) +
  tm_polygons(fill = "#f5a255") +
  tm_shape(low) +
  tm_polygons(fill = "#affff7") +
  tm_shape(mc_cities) +
  tm_bubbles(size = .45, col = "black", fill = "yellow") +
  tm_add_legend(
    type = "polygons",
    title = "RMP Proximity and People of Color",
    fill = c("#e84614", "#02bea5", "#f5a255", "#affff7"),
    labels = c(
      "High RMP + High People of Color",
      "High People of Color Only",
      "High RMP Only",
      "Neither"
    )
  ) +
  tm_add_legend(
    type = "symbols",
    title = "",
    fill = "yellow",
    col = "black",
    labels = "Communities"
  ) +
  tm_scalebar(position = c("left", "bottom")) +
  tm_compass(position = c("right", "top")) +
  tm_title_out(
    text = "Racial Demographics and Proximity to Hazardous Materials Facilities in Monterey County",
    fontface = "bold",
    position = tm_pos_out(cell.h = "center", cell.v = "top", pos.h = "center")
  ) +
  tm_layout(
    text.fontfamily = "sans",
    style = "natural",
    bg.color = "grey95",
    frame = TRUE,
    legend.text.size = 0.58,
    legend.title.size = 0.7,
    outer.margins = c(0.01, 0.01, 0.01, 0.01),
    asp = 0
  )
```